// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LMS.Server.Models;

public partial class Activity
{
    public int ActivityId { get; set; }

    public string ActivityName { get; set; }

    public int? ModuleId { get; set; }

    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();

    public virtual Module Module { get; set; }
}