// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LMS.Server.Models;

public partial class Document
{
    public int DocumentId { get; set; }

    public string DocumentName { get; set; }

    public int? UserId { get; set; }

    public int? ActivityId { get; set; }

    public virtual Activity Activity { get; set; }

    public virtual User User { get; set; }
}